version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: spring_mongo_react_blueprint
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: spring_redis_react_blueprint
    ports:
      - '6379:6379'
