spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/react_blueprint
      port: 27017
      database: react_blueprint
      host: localhost

    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 3000
  servlet:
    context-path: /api/v1

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538482F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

